/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include "game.h"

/* Header for class net_bumblebit_grapefruit_app_JNIWrapper */

#ifndef _Included_net_bumblebit_grapefruit_app_JNIWrapper
#define _Included_net_bumblebit_grapefruit_app_JNIWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_bumblebit_grapefruit_app_JNIWrapper
 * Method:    on_surface_created
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bumblebit_grapefruit_app_JNIWrapper_on_1surface_1created
  (JNIEnv * env, jclass cls) {
    on_surface_created();
}

/*
 * Class:     net_bumblebit_grapefruit_app_JNIWrapper
 * Method:    on_surface_changed
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_net_bumblebit_grapefruit_app_JNIWrapper_on_1surface_1changed
  (JNIEnv * env, jclass cls, jint width, jint height) {
    on_surface_changed();
}

/*
 * Class:     net_bumblebit_grapefruit_app_JNIWrapper
 * Method:    on_draw_frame
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_bumblebit_grapefruit_app_JNIWrapper_on_1draw_1frame
  (JNIEnv * env, jclass cls) {
    on_draw_frame();
}

#ifdef __cplusplus
}
#endif
#endif
